######################################################################
#                                                                    #
#                             NGA CONFIG                             #
#                                                                    #
#                              !WARNING!                             #
#    NEVER CHANGE SOMETHING IF YOU DON'T KNOW WHAT YOU'RE DOING!     #
#                                                                    #
# Plugin written by NevioGames.de                                    #
# Authors: Nevio, BloodRaid                                          #
# COPYRIGHT by NevioGames                                            #
######################################################################

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when NGAdmin loads, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe)
#   - Text with symbols is enclosed in single or double quotation marks

######################################################################
#                                                                    #
#                           SERVER SETTINGS                          #
#                                                                    #
#                              !WARNING!                             #
#    NEVER CHANGE SOMETHING IF YOU DON'T KNOW WHAT YOU'RE DOING!     #
######################################################################

server:
  # Name of the Server
  # NEVER CHANGE THIS IF YOU DON'T KNOW WHAT YOU'RE DOING!
  serverName: ''

  # Screen names of other servers e.g. (fb,lbah)
  # Separate multiple screens with a comma
  # Don't use the screen from this server
  # NEVER CHANGE THIS IF YOU DON'T KNOW WHAT YOU'RE DOING!
  serverScreen: ''

######################################################################
#                                                                    #
#                              SETTINGS                              #
#                                                                    #
######################################################################

settings:
  enable: false